name: Docker Image CI

on:
  push:
    branches: ["main", "release/*"]
  pull_request:
    branches: ["main", "release/*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --target dev -t gh-action-test

      - name: Run Tests
        run: docker run gh-action-test test
